Adds home bar icons
memory-thrasher/realworld-exercises-aurelia-on-asp pull request #3
Opened 2022-07-10 16:07 UTC by Stardagger

2022-07-10 17:04 UTC, memory-thrasher requested changes

2022-07-10 17:04 UTC, memory-thrasher commented on src/UI/src/shared/layouts/header-layout.html
> +        <<<<<<< HEAD
Remove the git tags

2022-07-10 17:04 UTC, memory-thrasher commented on src/UI/src/shared/layouts/header-layout.html
> +
Remove blank lines, add missing li close tag

2022-07-10 17:04 UTC, memory-thrasher commented on src/UI/src/shared/layouts/header-layout.html
> +          >>>>>>> 10ec65f (Adds home icons)
remove git tags

2022-07-10 17:10 UTC, memory-thrasher commented
Drop the top commit

2022-07-10 17:12 UTC, memory-thrasher commented on src/UI/src/shared/layouts/header-layout.html
> +        <li class="${'nav-item' + (activeRoute === 'logout' ? ' active' : '')}"
this li shouldn't even be here in this branch

2022-07-12 14:04 UTC, Stardagger commented on src/UI/src/shared/layouts/header-layout.html
> +        <li class="${'nav-item' + (activeRoute === 'logout' ? ' active' : '')}"
I'm  a  little bit confused about this one. the one on 43?

2022-07-14 02:00 UTC, merged